### PR TITLE
mo' goats

### PR DESCRIPTION
**Pull request by colby**

### CODE REVIEW

**Comment by nijotz** [comment]
"You are swarmed by bleating cloven workers. They rub and vibrate around you, causing serious burns and emotional damage." 👍 💯 📳 🔥

**Comment by qpfiffer** [comment]
You fucking broke travis, this goat is NOT stoked by your senseless master/slave antagonism

**Comment by qpfiffer** [comment]
LGTM deploying 📦

**Comment by nijotz** [comment]
We could change the documentation to be leader/worker, but that's too capitalist and could offend communist users.  We could call it parent/child, but think of the orphans.  What about thing1/thing2?

**Pull request merged**
