### PR TITLE
Feature/linkscraper cleanup

### PR DESCRIPTION
**Pull request by kyleterry**

### CODE REVIEW

**Comment by lykkin** [comment]
LGTM :shipit:

**Comment by qpfiffer** [comment]
THIS SEEMS LIKE MEANINGLESS TRIVIAL CODE CHANGES

PLEASE MERGE :+1: :package:

**Comment by kyleterry** [comment]
HEY ASSHOLE I FIXED SOME OF YOUR SHIT AND ADDED SOME OF MY SHIT SO I THINK I WILL MERGE :shipit: :package:

**Comment by nijotz** [comment]
$ git blame src/tenykslinkscraper/main.py | grep Tz
    d6d943cb (Nick Tzaperas   2013-09-05 14:09:47 -0700   2) import gevent
    d6d943cb (Nick Tzaperas   2013-09-05 14:09:47 -0700   3) import re
    d6d943cb (Nick Tzaperas   2013-09-05 14:09:47 -0700   4) import requests
    d6d943cb (Nick Tzaperas   2013-09-05 14:09:47 -0700   6) from BeautifulSoup import BeautifulSoup
    a72b0e20 (Nick Tzaperas   2013-09-05 14:42:57 -0700   7) from HTMLParser import HTMLParser
    d6d943cb (Nick Tzaperas   2013-09-05 14:09:47 -0700  55)

I bring tha deps.  You want deps?  I gots 'em, I just need a voided check.

**Comment by nijotz** [comment]
non-dank memes, just some month old mids

**Pull request merged**
